# Generated by Django 5.1.5 on 2025-01-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_product_description1_product_email_product_message_and_more'),
    ]

