# Generated by Django 5.1.5 on 2025-02-01 12:51

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_product_email_product_message_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(default=1, help_text='Тут нужно писать описание того как этот товар готовили', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.TextField(default=1, unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title1',
            field=models.CharField(default=1, help_text='Тут нужно писать прозвище товара', max_length=255, verbose_name='Прозвище'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='SLUG')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная категория')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='settings.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='settings.category'),
        ),
    ]
